# Generated by Django 5.0 on 2025-12-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('time_of_day', models.CharField(max_length=100)),
                ('is_taken', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('color_hex', models.CharField(default='#C6E2B5', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_name', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(default='English', max_length=50)),
                ('medical_condition', models.CharField(default='General', max_length=255)),
                ('current_status', models.CharField(choices=[('Stable', 'Stable'), ('Critical', 'Critical'), ('High', 'High')], default='Stable', max_length=20)),
                ('current_mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('last_heart_rate', models.IntegerField(default=72)),
                ('last_temperature', models.FloatField(default=98.6)),
                ('last_blood_pressure', models.CharField(default='120/80', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('steps', models.IntegerField(default=0)),
                ('sleep_hours', models.FloatField(default=0.0)),
                ('blood_pressure', models.CharField(default='120/80', max_length=20)),
                ('temperature', models.FloatField(default=98.6)),
                ('oxygen_level', models.IntegerField(default=98)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
