# Generated by Django 5.0 on 2025-12-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(help_text='Duration string like 15:32', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Missed', 'Missed'), ('Ongoing', 'Ongoing')], max_length=20)),
                ('call_type', models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_user_sender', models.BooleanField(default=True, help_text='True if sent by user, False if sent by AI')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
